- name: Get GKE Credentials
  uses: google-github-actions/get-gke-credentials@v0.2.1
steps:

- id: auth

  uses: google-github-actions/auth@v0.4.0

  with:

    workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'

    service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

- id: get-credentials

  uses: google-github-actions/get-gke-credentials@v0.3.0

  with:

    cluster_name: my-cluster

    location: us-central1-a

# The KUBECONFIG env var is automatically exported and picked up by kubectl.

- id: get-pods

  run: kubectl get pods

